### ISSUE TITLE
List Index out of range

### ISSUE THREAD

**Issue by Rdna123** [Modvengers/BeachParty#2]
Error I received when going to beach area.
```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/gamecode/adventureCode/on_map.rpy", line 132, in script
    python:
  File "game/gamecode/adventureCode/on_map.rpy", line 138, in <module>
    availableAdventures = GetAdventureNames(loc)
  File "game/gamecode/adventureCode/on_map.rpy", line 204, in GetAdventureNames
    questProgress = ProgressAdventure[adventureIndex]
IndexError: list index out of range

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/gamecode/adventureCode/on_map.rpy", line 132, in script
    python:
  File "C:\Users\chknm\Downloads\Extra\MonGirlDreams-Alpha-v23.5b-pc\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\chknm\Downloads\Extra\MonGirlDreams-Alpha-v23.5b-pc\renpy\python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/gamecode/adventureCode/on_map.rpy", line 138, in <module>
    availableAdventures = GetAdventureNames(loc)
  File "game/gamecode/adventureCode/on_map.rpy", line 204, in GetAdventureNames
    questProgress = ProgressAdventure[adventureIndex]
  File "C:\Users\chknm\Downloads\Extra\MonGirlDreams-Alpha-v23.5b-pc\renpy\python.py", line 847, in __getitem__
    rv = list.__getitem__(self, index)
IndexError: list index out of range

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Monster Girl Dreams Alpha-v23.5b
Fri Dec 04 12:08:35 2020
```

**Comment by KaaMGD** [comment]
I can't seem to replicate this issue. Can you provide more context where exactly it happened?

**Comment by Rdna123** [comment]
I had put the extracted mod, called beach, into mod folder and started game
then the error occurred

**Comment by KaaMGD** [comment]
That is really strange. I can only suggest trying with a new fresh version of the game and the latest mod version, as I cannot replicate the issue in any form.

**Comment by Rdna123** [comment]
Did try a fresh install, I am on Windows that may be a problem too but I
can play other mods just fine, have tried playing without other mods.

**Comment by Rdna123** [comment]
The mod only works in fresh saves not ongoing saves.

**Comment by KaaMGD** [comment]
On your ongoing saves, have you been to beach before? You should have a 'Speedo' key item in that case.
If you both been to the beach and the speedo was somehow lost, then that error could happen I think.
You should be able to restore the speedo with a console command: player.inventory.give("Speedo", 1)
For guidelines on how to enable and use the console you can check the wiki.

**Comment by Rdna123** [comment]
The error happens on ongoing saves that never had the mod before, I will try to use the console command to see if that fixes it.


Edit: When I go to the beach the first time in ongoing saves is when it crashes

**Comment by KaaMGD** [comment]
Can you upload your ongoing save somewhere?
The saves should be contained in C:\Users\YOURNAME\AppData\Roaming\RenPy\MonGirl-1496073722

**Comment by Rdna123** [comment]
This is my save
[MySave.zip](https://github.com/KaaMGD/BeachParty/files/5681448/MySave.zip)


I did believe I found out what I did wrong, I did not exit the game completely when I first tried to play with the mod.

**Comment by Rdna123** [comment]
I misinterpreted the installing mod section thinking I just had to exit the save I was in.
